In [74]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix , accuracy_score, classification_report



In [75]:
data = pd.read_csv("Pubg_stats.csv")
data.head()


Unnamed: 0    Player_Name  Matches_Played  Kills  Deaths  Assists  \
0           0  StealthMaster             250    587     143       98   
1           1     SniperLion             312    823     218      112   
2           2     NinjaGamer             186    492      84       56   
3           3  ThunderStrike             409    923     267      134   
4           4     SpeedDemon             143    368      68       42   

   Damage_Dealt  Headshots  Wins      Rank  Revives  Distance_Traveled  \
0         15243        234    32      Gold       67              72560   
1         18975        312    42   Diamond       95              89042   
2         11786        156    28  Platinum       48              60924   
3         21037        288    55    Silver      128              98234   
4          9865        123    20      Gold       36              52072   

   Weapons_Used  Time_Survived  Top_10s  
0            12          28976      145  
1            15          33652      189  
2            10          21764       97  
3            18          40128      258  
4             8          16834       72

In [76]:
from sklearn.preprocessing import StandardScaler
scalar = StandardScaler()
columns_to_drop = ['Unnamed: 0', 'Player_Name','Rank']
columns_to_scale = ['Matches_Played','Kills','Deaths','Assists','Damage_Dealt','Headshots','Wins','Top_10s','Revives','Distance_Traveled','Weapons_Used','Time_Survived']
dropped_columns = data[columns_to_drop]
data_dropped_columns = data.drop(columns_to_drop, axis=1)
scaled_features = scalar.fit_transform(data_dropped_columns)
df_scaled_features = pd.DataFrame(scaled_features, columns = columns_to_scale)
integrated_df = pd.concat([df_scaled_features, dropped_columns], axis=1)


In [77]:
from sklearn.model_selection import train_test_split
X = df_scaled_features
Y = data['Rank']

x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2) 

In [78]:
from sklearn.neighbors import KNeighborsClassifier
error_rate=[]
for i in range(1,30):
    knn = KNeighborsClassifier(n_neighbors = i)
    knn.fit(x_train, y_train)
    pred = knn.predict(x_test)
    error_rate.append(np.mean(pred != y_test))


C:\Users\Saad\Anaconda3\lib\site-packages\sklearn\neighbors\base.py:908: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  self._y = np.empty(y.shape, dtype=np.int)
C:\Users\Saad\Anaconda3\lib\site-packages\sklearn\neighbors\base.py:908: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, chec

C:\Users\Saad\Anaconda3\lib\site-packages\sklearn\neighbors\base.py:908: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  self._y = np.empty(y.shape, dtype=np.int)
C:\Users\Saad\Anaconda3\lib\site-packages\sklearn\neighbors\base.py:908: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, chec

In [79]:
knn = KNeighborsClassifier(n_neighbors = 5)
knn.fit(x_train, y_train)
prediction_of_best_KNN = knn.predict(x_test)

C:\Users\Saad\Anaconda3\lib\site-packages\sklearn\neighbors\base.py:908: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  self._y = np.empty(y.shape, dtype=np.int)


In [80]:
from sklearn.metrics import classification_report, confusion_matrix
print("Classification Report\n\n")
print(classification_report(y_test, prediction_of_best_KNN))
print("CONFUSION MATRIX\n\n")
print(confusion_matrix(y_test, prediction_of_best_KNN))


Classification Report


              precision    recall  f1-score   support

     Diamond       0.87      0.93      0.90        14
        Gold       0.90      0.90      0.90        10
    Platinum       0.94      0.85      0.89        20
      Silver       0.50      1.00      0.67         1

    accuracy                           0.89        45
   macro avg       0.80      0.92      0.84        45
weighted avg       0.90      0.89      0.89        45

CONFUSION MATRIX


[[13  0  1  0]
 [ 0  9  0  1]
 [ 2  1 17  0]
 [ 0  0  0  1]]
